### ISSUE TITLE
Mention art attributions

### ISSUE THREAD

**Issue by OpenSourceJesus** [Master109/Grid-Game#7]

**Comment by OpenSourceJesus** [comment]
"Icon made by Vectors Market from www.flaticon.com"
"Icon made by Those Icons from www.flaticon.com"
"Icon made by Smashicons from www.flaticon.com"
"Icon made by Payungkead from www.flaticon.com"
"Icon made by Freepik from www.flaticon.com"
"Icon made by Good Ware from www.flaticon.com"

**Comment by Master109** [comment]
"Icon made by Those Icons from www.flaticon.com"
